### ISSUE TITLE
APK解析包出现问题

### ISSUE THREAD

**Issue by sonichy** [xxxyanchenxxx/QqDecrpt#2]
Android Studio 3.0 出现USB调试可以运行，发送给别的手机解析包出现问题。

**Comment by xxxyanchenxxx** [comment]
adb install 安装看下出错原因。另外根目录下提供了个demo.apk，可以用来测试。

**Comment by sonichy** [comment]
我汗了，我的意思是直接安装demo.apk解析包出错，并没有在 Android Studio 里调试。
