### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by nidhoggfgg** [xxxyanchenxxx/QqDecrpt#4]
这个aide编译不了，如何解决，还有，那个QQ聊天记录不是在data/data/QQ包名/QQ号indexMsg.db里面么

**Comment by vikieow** [comment]
大神，想咨询下群通知那个表里面的数据，不能接触群号，还望指导一下

**Comment by xxxyanchenxxx** [comment]
> 这个aide编译不了，如何解决，还有，那个QQ聊天记录不是在data/data/QQ包名/QQ号indexMsg.db里面么

paste your build error info pls?

**Comment by YehFeng** [comment]
大神，想咨询下，最近的QQ数据库，加密貌似加盐了

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
